// Datos generados con perplexity
import { BaptismPerson } from "./data-table";

const minister = "Luis";

export const data: BaptismPerson[] = [
  {
    dni: "20000",
    fullName: "Juan Carlos",
    godmotherName: "Marta Flores",
    godfatherName: "Jose Ramos",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20001",
    fullName: "Maria Lopez",
    godmotherName: "Ana Martinez",
    godfatherName: "Pedro Sanchez",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20002",
    fullName: "Pedro Rodriguez",
    godmotherName: "Laura Gomez",
    godfatherName: "Antonio Perez",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20003",
    fullName: "Ana Garcia",
    godmotherName: "Elena Fernandez",
    godfatherName: "Javier Jimenez",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20004",
    fullName: "Sofia Ramirez",
    godmotherName: "Isabel Torres",
    godfatherName: "Manuel Ruiz",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20005",
    fullName: "Carlos Martinez",
    godmotherName: "Carmen Soto",
    godfatherName: "Raul Navarro",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20006",
    fullName: "Laura Fernandez",
    godmotherName: "Sara Diaz",
    godfatherName: "Pablo Martin",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20007",
    fullName: "Antonio Sanchez",
    godmotherName: "Luisa Romero",
    godfatherName: "Francisco Herrera",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20008",
    fullName: "Elena Jimenez",
    godmotherName: "Raquel Vargas",
    godfatherName: "Alberto Medina",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20009",
    fullName: "Manuel Perez",
    godmotherName: "Natalia Ortega",
    godfatherName: "Diego Castro",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20010",
    fullName: "Isabel Ruiz",
    godmotherName: "Patricia Navarro",
    godfatherName: "Jorge Soto",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20011",
    fullName: "Javier Gomez",
    godmotherName: "Monica Martin",
    godfatherName: "Roberto Garcia",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20012",
    fullName: "Carmen Torres",
    godmotherName: "Beatriz Perez",
    godfatherName: "Julio Fernandez",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20013",
    fullName: "Raul Navarro",
    godmotherName: "Marina Ruiz",
    godfatherName: "Hector Sanchez",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20014",
    fullName: "Sara Diaz",
    godmotherName: "Cristina Jimenez",
    godfatherName: "Miguel Lopez",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20015",
    fullName: "Francisco Herrera",
    godmotherName: "Lorena Perez",
    godfatherName: "Daniel Ramirez",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20016",
    fullName: "Alberto Medina",
    godmotherName: "Silvia Gomez",
    godfatherName: "Gloria Torres",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20017",
    fullName: "Diego Castro",
    godmotherName: "Eva Navarro",
    godfatherName: "Andres Martin",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20018",
    fullName: "Jorge Soto",
    godmotherName: "Pilar Fernandez",
    godfatherName: "Marcos Sanchez",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20019",
    fullName: "Roberto Garcia",
    godmotherName: "Nerea Torres",
    godfatherName: "Ivan Perez",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20020",
    fullName: "Julio Fernandez",
    godmotherName: "Alicia Ruiz",
    godfatherName: "Ruben Diaz",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20021",
    fullName: "Hector Sanchez",
    godmotherName: "Celia Diaz",
    godfatherName: "Oscar Gomez",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20022",
    fullName: "Miguel Lopez",
    godmotherName: "Ines Garcia",
    godfatherName: "Victor Martin",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20023",
    fullName: "Daniel Ramirez",
    godmotherName: "Rosa Sanchez",
    godfatherName: "Pedro Torres",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20024",
    fullName: "Gloria Torres",
    godmotherName: "Clara Perez",
    godfatherName: "Sergio Ruiz",
    ministerOfTheSacrament: minister,
  },
  {
    dni: "20025",
    fullName: "Andres Martin",
    godmotherName: "Elena Fernandez",
    godfatherName: "Luis Garcia",
    ministerOfTheSacrament: minister,
  },
];
